/* ***** BEGIN LICENSE BLOCK *****
 * Version: MPL 1.1/GPL 2.0/LGPL 2.1
 *
 * The contents of this file are subject to the Mozilla Public License Version
 * 1.1 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the
 * License.
 *
 * The Original Code is mozilla.org code.
 *
 * The Initial Developer of the Original Code is
 * Netscape Communications Corporation.
 * Portions created by the Initial Developer are Copyright (C) 1998
 * the Initial Developer. All Rights Reserved.
 *
 * Alternatively, the contents of this file may be used under the terms of
 * either of the GNU General Public License Version 2 or later (the "GPL"),
 * or the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
 * in which case the provisions of the GPL or the LGPL are applicable instead
 * of those above. If you wish to allow use of your version of this file only
 * under the terms of either the GPL or the LGPL, and not to allow others to
 * use your version of this file under the terms of the MPL, indicate your
 * decision by deleting the provisions above and replace them with the notice
 * and other provisions required by the GPL or the LGPL. If you do not delete
 * the provisions above, a recipient may use your version of this file under
 * the terms of any one of the MPL, the GPL or the LGPL.
 *
 * ***** END LICENSE BLOCK ***** */
/* 
 * DO NOT EDIT THIS DOCUMENT MANUALLY !!!
 * THIS FILE IS AUTOMATICALLY GENERATED BY THE TOOLS UNDER
 *    AutoDetect/tools/
 */
package com.wxiwei.office.thirdpart.mozilla.intl.chardet

class nsHZVerifier : nsVerifier() {
    override fun cclass(): IntArray? {
        return cclass
    }

    override fun states(): IntArray? {
        return states
    }

    override fun stFactor(): Int {
        return stFactor
    }

    override fun charset(): String? {
        return charset
    }

    init {
        cclass = IntArray(256 / 8)

        cclass!![0] =
            (((((((((((0) shl 4) or (0)) as kotlin.Int)) shl 8) or (((((0) shl 4) or (0)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((0) shl 4) or (0)) as kotlin.Int)) shl 8) or (((((0) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)))
        cclass!![1] =
            (((((((((((0) shl 4) or (0)) as kotlin.Int)) shl 8) or (((((0) shl 4) or (0)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((0) shl 4) or (0)) as kotlin.Int)) shl 8) or (((((0) shl 4) or (0)) as kotlin.Int))) as kotlin.Int)))
        cclass!![2] =
            (((((((((((0) shl 4) or (0)) as kotlin.Int)) shl 8) or (((((0) shl 4) or (0)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((0) shl 4) or (0)) as kotlin.Int)) shl 8) or (((((0) shl 4) or (0)) as kotlin.Int))) as kotlin.Int)))
        cclass!![3] =
            (((((((((((0) shl 4) or (0)) as kotlin.Int)) shl 8) or (((((0) shl 4) or (0)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((1) shl 4) or (0)) as kotlin.Int)) shl 8) or (((((0) shl 4) or (0)) as kotlin.Int))) as kotlin.Int)))
        cclass!![4] =
            (((((((((((0) shl 4) or (0)) as kotlin.Int)) shl 8) or (((((0) shl 4) or (0)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((0) shl 4) or (0)) as kotlin.Int)) shl 8) or (((((0) shl 4) or (0)) as kotlin.Int))) as kotlin.Int)))
        cclass!![5] =
            (((((((((((0) shl 4) or (0)) as kotlin.Int)) shl 8) or (((((0) shl 4) or (0)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((0) shl 4) or (0)) as kotlin.Int)) shl 8) or (((((0) shl 4) or (0)) as kotlin.Int))) as kotlin.Int)))
        cclass!![6] =
            (((((((((((0) shl 4) or (0)) as kotlin.Int)) shl 8) or (((((0) shl 4) or (0)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((0) shl 4) or (0)) as kotlin.Int)) shl 8) or (((((0) shl 4) or (0)) as kotlin.Int))) as kotlin.Int)))
        cclass!![7] =
            (((((((((((0) shl 4) or (0)) as kotlin.Int)) shl 8) or (((((0) shl 4) or (0)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((0) shl 4) or (0)) as kotlin.Int)) shl 8) or (((((0) shl 4) or (0)) as kotlin.Int))) as kotlin.Int)))
        cclass!![8] =
            (((((((((((0) shl 4) or (0)) as kotlin.Int)) shl 8) or (((((0) shl 4) or (0)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((0) shl 4) or (0)) as kotlin.Int)) shl 8) or (((((0) shl 4) or (0)) as kotlin.Int))) as kotlin.Int)))
        cclass!![9] =
            (((((((((((0) shl 4) or (0)) as kotlin.Int)) shl 8) or (((((0) shl 4) or (0)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((0) shl 4) or (0)) as kotlin.Int)) shl 8) or (((((0) shl 4) or (0)) as kotlin.Int))) as kotlin.Int)))
        cclass!![10] =
            (((((((((((0) shl 4) or (0)) as kotlin.Int)) shl 8) or (((((0) shl 4) or (0)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((0) shl 4) or (0)) as kotlin.Int)) shl 8) or (((((0) shl 4) or (0)) as kotlin.Int))) as kotlin.Int)))
        cclass!![11] =
            (((((((((((0) shl 4) or (0)) as kotlin.Int)) shl 8) or (((((0) shl 4) or (0)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((0) shl 4) or (0)) as kotlin.Int)) shl 8) or (((((0) shl 4) or (0)) as kotlin.Int))) as kotlin.Int)))
        cclass!![12] =
            (((((((((((0) shl 4) or (0)) as kotlin.Int)) shl 8) or (((((0) shl 4) or (0)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((0) shl 4) or (0)) as kotlin.Int)) shl 8) or (((((0) shl 4) or (0)) as kotlin.Int))) as kotlin.Int)))
        cclass!![13] =
            (((((((((((0) shl 4) or (0)) as kotlin.Int)) shl 8) or (((((0) shl 4) or (0)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((0) shl 4) or (0)) as kotlin.Int)) shl 8) or (((((0) shl 4) or (0)) as kotlin.Int))) as kotlin.Int)))
        cclass!![14] =
            (((((((((((0) shl 4) or (0)) as kotlin.Int)) shl 8) or (((((0) shl 4) or (0)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((0) shl 4) or (0)) as kotlin.Int)) shl 8) or (((((0) shl 4) or (0)) as kotlin.Int))) as kotlin.Int)))
        cclass!![15] =
            (((((((((((0) shl 4) or (2)) as kotlin.Int)) shl 8) or (((((5) shl 4) or (0)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((4) shl 4) or (0)) as kotlin.Int)) shl 8) or (((((0) shl 4) or (0)) as kotlin.Int))) as kotlin.Int)))
        cclass!![16] =
            (((((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)))
        cclass!![17] =
            (((((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)))
        cclass!![18] =
            (((((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)))
        cclass!![19] =
            (((((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)))
        cclass!![20] =
            (((((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)))
        cclass!![21] =
            (((((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)))
        cclass!![22] =
            (((((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)))
        cclass!![23] =
            (((((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)))
        cclass!![24] =
            (((((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)))
        cclass!![25] =
            (((((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)))
        cclass!![26] =
            (((((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)))
        cclass!![27] =
            (((((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)))
        cclass!![28] =
            (((((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)))
        cclass!![29] =
            (((((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)))
        cclass!![30] =
            (((((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)))
        cclass!![31] =
            (((((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)))



        states = IntArray(6)

        states!![0] =
            (((((((((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int)) shl 8) or (((((nsVerifier.Companion.eStart).toInt() shl 4) or (nsVerifier.Companion.eStart).toInt()) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((nsVerifier.Companion.eStart).toInt() shl 4) or (3)) as kotlin.Int)) shl 8) or (((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eStart).toInt()) as kotlin.Int))) as kotlin.Int)))
        states!![1] =
            (((((((((((nsVerifier.Companion.eItsMe).toInt() shl 4) or (nsVerifier.Companion.eItsMe).toInt()) as kotlin.Int)) shl 8) or (((((nsVerifier.Companion.eItsMe).toInt() shl 4) or (nsVerifier.Companion.eItsMe).toInt()) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int)) shl 8) or (((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int))) as kotlin.Int)))
        states!![2] =
            (((((((((((nsVerifier.Companion.eError).toInt() shl 4) or (4)) as kotlin.Int)) shl 8) or (((((nsVerifier.Companion.eStart).toInt() shl 4) or (nsVerifier.Companion.eStart).toInt()) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int)) shl 8) or (((((nsVerifier.Companion.eItsMe).toInt() shl 4) or (nsVerifier.Companion.eItsMe).toInt()) as kotlin.Int))) as kotlin.Int)))
        states!![3] =
            (((((((((((nsVerifier.Companion.eError).toInt() shl 4) or (4)) as kotlin.Int)) shl 8) or (((((5) shl 4) or (5)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((nsVerifier.Companion.eError).toInt() shl 4) or (6)) as kotlin.Int)) shl 8) or (((((nsVerifier.Companion.eError).toInt() shl 4) or (5)) as kotlin.Int))) as kotlin.Int)))
        states!![4] =
            (((((((((((nsVerifier.Companion.eError).toInt() shl 4) or (4)) as kotlin.Int)) shl 8) or (((((nsVerifier.Companion.eError).toInt() shl 4) or (4)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((4) shl 4) or (4)) as kotlin.Int)) shl 8) or (((((nsVerifier.Companion.eError).toInt() shl 4) or (4)) as kotlin.Int))) as kotlin.Int)))
        states!![5] =
            (((((((((((nsVerifier.Companion.eStart).toInt() shl 4) or (nsVerifier.Companion.eStart).toInt()) as kotlin.Int)) shl 8) or (((((nsVerifier.Companion.eStart).toInt() shl 4) or (nsVerifier.Companion.eStart).toInt()) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((nsVerifier.Companion.eStart).toInt() shl 4) or (nsVerifier.Companion.eStart).toInt()) as kotlin.Int)) shl 8) or (((((nsVerifier.Companion.eItsMe).toInt() shl 4) or (4)) as kotlin.Int))) as kotlin.Int)))



        charset = "HZ-GB-2312"
        stFactor = 6
    }

    override fun isUCS2(): Boolean {
        return false
    }


    companion object {
        var cclass: IntArray? = null
        var states: IntArray? = null
        var stFactor: Int = 0
        var charset: String? = null
    }
}
