/* ***** BEGIN LICENSE BLOCK *****
 * Version: MPL 1.1/GPL 2.0/LGPL 2.1
 *
 * The contents of this file are subject to the Mozilla Public License Version
 * 1.1 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the
 * License.
 *
 * The Original Code is mozilla.org code.
 *
 * The Initial Developer of the Original Code is
 * Netscape Communications Corporation.
 * Portions created by the Initial Developer are Copyright (C) 1998
 * the Initial Developer. All Rights Reserved.
 *
 * Alternatively, the contents of this file may be used under the terms of
 * either of the GNU General Public License Version 2 or later (the "GPL"),
 * or the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
 * in which case the provisions of the GPL or the LGPL are applicable instead
 * of those above. If you wish to allow use of your version of this file only
 * under the terms of either the GPL or the LGPL, and not to allow others to
 * use your version of this file under the terms of the MPL, indicate your
 * decision by deleting the provisions above and replace them with the notice
 * and other provisions required by the GPL or the LGPL. If you do not delete
 * the provisions above, a recipient may use your version of this file under
 * the terms of any one of the MPL, the GPL or the LGPL.
 *
 * ***** END LICENSE BLOCK ***** */
/* 
 * DO NOT EDIT THIS DOCUMENT MANUALLY !!!
 * THIS FILE IS AUTOMATICALLY GENERATED BY THE TOOLS UNDER
 *    AutoDetect/tools/
 */
package com.wxiwei.office.thirdpart.mozilla.intl.chardet

class nsUTF8Verifier : nsVerifier() {
    override fun cclass(): IntArray? {
        return cclass
    }

    override fun states(): IntArray? {
        return states
    }

    override fun stFactor(): Int {
        return stFactor
    }

    override fun charset(): String? {
        return charset
    }

    init {
        cclass = IntArray(256 / 8)

        cclass!![0] =
            (((((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)))
        cclass!![1] =
            (((((((((((0) shl 4) or (0)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)))
        cclass!![2] =
            (((((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)))
        cclass!![3] =
            (((((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((0) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)))
        cclass!![4] =
            (((((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)))
        cclass!![5] =
            (((((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)))
        cclass!![6] =
            (((((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)))
        cclass!![7] =
            (((((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)))
        cclass!![8] =
            (((((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)))
        cclass!![9] =
            (((((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)))
        cclass!![10] =
            (((((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)))
        cclass!![11] =
            (((((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)))
        cclass!![12] =
            (((((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)))
        cclass!![13] =
            (((((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)))
        cclass!![14] =
            (((((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)))
        cclass!![15] =
            (((((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((1) shl 4) or (1)) as kotlin.Int)) shl 8) or (((((1) shl 4) or (1)) as kotlin.Int))) as kotlin.Int)))
        cclass!![16] =
            (((((((((((3) shl 4) or (3)) as kotlin.Int)) shl 8) or (((((3) shl 4) or (3)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((2) shl 4) or (2)) as kotlin.Int)) shl 8) or (((((2) shl 4) or (2)) as kotlin.Int))) as kotlin.Int)))
        cclass!![17] =
            (((((((((((4) shl 4) or (4)) as kotlin.Int)) shl 8) or (((((4) shl 4) or (4)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((4) shl 4) or (4)) as kotlin.Int)) shl 8) or (((((4) shl 4) or (4)) as kotlin.Int))) as kotlin.Int)))
        cclass!![18] =
            (((((((((((4) shl 4) or (4)) as kotlin.Int)) shl 8) or (((((4) shl 4) or (4)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((4) shl 4) or (4)) as kotlin.Int)) shl 8) or (((((4) shl 4) or (4)) as kotlin.Int))) as kotlin.Int)))
        cclass!![19] =
            (((((((((((4) shl 4) or (4)) as kotlin.Int)) shl 8) or (((((4) shl 4) or (4)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((4) shl 4) or (4)) as kotlin.Int)) shl 8) or (((((4) shl 4) or (4)) as kotlin.Int))) as kotlin.Int)))
        cclass!![20] =
            (((((((((((5) shl 4) or (5)) as kotlin.Int)) shl 8) or (((((5) shl 4) or (5)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((5) shl 4) or (5)) as kotlin.Int)) shl 8) or (((((5) shl 4) or (5)) as kotlin.Int))) as kotlin.Int)))
        cclass!![21] =
            (((((((((((5) shl 4) or (5)) as kotlin.Int)) shl 8) or (((((5) shl 4) or (5)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((5) shl 4) or (5)) as kotlin.Int)) shl 8) or (((((5) shl 4) or (5)) as kotlin.Int))) as kotlin.Int)))
        cclass!![22] =
            (((((((((((5) shl 4) or (5)) as kotlin.Int)) shl 8) or (((((5) shl 4) or (5)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((5) shl 4) or (5)) as kotlin.Int)) shl 8) or (((((5) shl 4) or (5)) as kotlin.Int))) as kotlin.Int)))
        cclass!![23] =
            (((((((((((5) shl 4) or (5)) as kotlin.Int)) shl 8) or (((((5) shl 4) or (5)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((5) shl 4) or (5)) as kotlin.Int)) shl 8) or (((((5) shl 4) or (5)) as kotlin.Int))) as kotlin.Int)))
        cclass!![24] =
            (((((((((((6) shl 4) or (6)) as kotlin.Int)) shl 8) or (((((6) shl 4) or (6)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((6) shl 4) or (6)) as kotlin.Int)) shl 8) or (((((0) shl 4) or (0)) as kotlin.Int))) as kotlin.Int)))
        cclass!![25] =
            (((((((((((6) shl 4) or (6)) as kotlin.Int)) shl 8) or (((((6) shl 4) or (6)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((6) shl 4) or (6)) as kotlin.Int)) shl 8) or (((((6) shl 4) or (6)) as kotlin.Int))) as kotlin.Int)))
        cclass!![26] =
            (((((((((((6) shl 4) or (6)) as kotlin.Int)) shl 8) or (((((6) shl 4) or (6)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((6) shl 4) or (6)) as kotlin.Int)) shl 8) or (((((6) shl 4) or (6)) as kotlin.Int))) as kotlin.Int)))
        cclass!![27] =
            (((((((((((6) shl 4) or (6)) as kotlin.Int)) shl 8) or (((((6) shl 4) or (6)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((6) shl 4) or (6)) as kotlin.Int)) shl 8) or (((((6) shl 4) or (6)) as kotlin.Int))) as kotlin.Int)))
        cclass!![28] =
            (((((((((((8) shl 4) or (8)) as kotlin.Int)) shl 8) or (((((8) shl 4) or (8)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((8) shl 4) or (8)) as kotlin.Int)) shl 8) or (((((8) shl 4) or (7)) as kotlin.Int))) as kotlin.Int)))
        cclass!![29] =
            (((((((((((8) shl 4) or (8)) as kotlin.Int)) shl 8) or (((((9) shl 4) or (8)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((8) shl 4) or (8)) as kotlin.Int)) shl 8) or (((((8) shl 4) or (8)) as kotlin.Int))) as kotlin.Int)))
        cclass!![30] =
            (((((((((((11) shl 4) or (11)) as kotlin.Int)) shl 8) or (((((11) shl 4) or (11)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((11) shl 4) or (11)) as kotlin.Int)) shl 8) or (((((11) shl 4) or (10)) as kotlin.Int))) as kotlin.Int)))
        cclass!![31] =
            (((((((((((0) shl 4) or (0)) as kotlin.Int)) shl 8) or (((((15) shl 4) or (14)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((13) shl 4) or (13)) as kotlin.Int)) shl 8) or (((((13) shl 4) or (12)) as kotlin.Int))) as kotlin.Int)))



        states = IntArray(26)

        states!![0] =
            (((((((((((10) shl 4) or (12)) as kotlin.Int)) shl 8) or (((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int)) shl 8) or (((((nsVerifier.Companion.eStart).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int))) as kotlin.Int)))
        states!![1] =
            (((((((((((3) shl 4) or (4)) as kotlin.Int)) shl 8) or (((((5) shl 4) or (6)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((7) shl 4) or (8)) as kotlin.Int)) shl 8) or (((((11) shl 4) or (9)) as kotlin.Int))) as kotlin.Int)))
        states!![2] =
            (((((((((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int)) shl 8) or (((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int)) shl 8) or (((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int))) as kotlin.Int)))
        states!![3] =
            (((((((((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int)) shl 8) or (((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int)) shl 8) or (((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int))) as kotlin.Int)))
        states!![4] =
            (((((((((((nsVerifier.Companion.eItsMe).toInt() shl 4) or (nsVerifier.Companion.eItsMe).toInt()) as kotlin.Int)) shl 8) or (((((nsVerifier.Companion.eItsMe).toInt() shl 4) or (nsVerifier.Companion.eItsMe).toInt()) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((nsVerifier.Companion.eItsMe).toInt() shl 4) or (nsVerifier.Companion.eItsMe).toInt()) as kotlin.Int)) shl 8) or (((((nsVerifier.Companion.eItsMe).toInt() shl 4) or (nsVerifier.Companion.eItsMe).toInt()) as kotlin.Int))) as kotlin.Int)))
        states!![5] =
            (((((((((((nsVerifier.Companion.eItsMe).toInt() shl 4) or (nsVerifier.Companion.eItsMe).toInt()) as kotlin.Int)) shl 8) or (((((nsVerifier.Companion.eItsMe).toInt() shl 4) or (nsVerifier.Companion.eItsMe).toInt()) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((nsVerifier.Companion.eItsMe).toInt() shl 4) or (nsVerifier.Companion.eItsMe).toInt()) as kotlin.Int)) shl 8) or (((((nsVerifier.Companion.eItsMe).toInt() shl 4) or (nsVerifier.Companion.eItsMe).toInt()) as kotlin.Int))) as kotlin.Int)))
        states!![6] =
            (((((((((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int)) shl 8) or (((((5) shl 4) or (5)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((5) shl 4) or (5)) as kotlin.Int)) shl 8) or (((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int))) as kotlin.Int)))
        states!![7] =
            (((((((((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int)) shl 8) or (((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int)) shl 8) or (((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int))) as kotlin.Int)))
        states!![8] =
            (((((((((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int)) shl 8) or (((((5) shl 4) or (5)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((5) shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int)) shl 8) or (((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int))) as kotlin.Int)))
        states!![9] =
            (((((((((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int)) shl 8) or (((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int)) shl 8) or (((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int))) as kotlin.Int)))
        states!![10] =
            (((((((((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int)) shl 8) or (((((7) shl 4) or (7)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((7) shl 4) or (7)) as kotlin.Int)) shl 8) or (((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int))) as kotlin.Int)))
        states!![11] =
            (((((((((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int)) shl 8) or (((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int)) shl 8) or (((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int))) as kotlin.Int)))
        states!![12] =
            (((((((((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int)) shl 8) or (((((7) shl 4) or (7)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int)) shl 8) or (((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int))) as kotlin.Int)))
        states!![13] =
            (((((((((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int)) shl 8) or (((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int)) shl 8) or (((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int))) as kotlin.Int)))
        states!![14] =
            (((((((((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int)) shl 8) or (((((9) shl 4) or (9)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((9) shl 4) or (9)) as kotlin.Int)) shl 8) or (((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int))) as kotlin.Int)))
        states!![15] =
            (((((((((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int)) shl 8) or (((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int)) shl 8) or (((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int))) as kotlin.Int)))
        states!![16] =
            (((((((((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int)) shl 8) or (((((9) shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int)) shl 8) or (((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int))) as kotlin.Int)))
        states!![17] =
            (((((((((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int)) shl 8) or (((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int)) shl 8) or (((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int))) as kotlin.Int)))
        states!![18] =
            (((((((((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int)) shl 8) or (((((12) shl 4) or (12)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((12) shl 4) or (12)) as kotlin.Int)) shl 8) or (((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int))) as kotlin.Int)))
        states!![19] =
            (((((((((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int)) shl 8) or (((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int)) shl 8) or (((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int))) as kotlin.Int)))
        states!![20] =
            (((((((((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int)) shl 8) or (((((12) shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int)) shl 8) or (((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int))) as kotlin.Int)))
        states!![21] =
            (((((((((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int)) shl 8) or (((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int)) shl 8) or (((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int))) as kotlin.Int)))
        states!![22] =
            (((((((((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int)) shl 8) or (((((nsVerifier.Companion.eError).toInt() shl 4) or (12)) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((12) shl 4) or (12)) as kotlin.Int)) shl 8) or (((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int))) as kotlin.Int)))
        states!![23] =
            (((((((((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int)) shl 8) or (((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int)) shl 8) or (((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int))) as kotlin.Int)))
        states!![24] =
            (((((((((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int)) shl 8) or (((((nsVerifier.Companion.eStart).toInt() shl 4) or (nsVerifier.Companion.eStart).toInt()) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((nsVerifier.Companion.eStart).toInt() shl 4) or (nsVerifier.Companion.eStart).toInt()) as kotlin.Int)) shl 8) or (((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int))) as kotlin.Int)))
        states!![25] =
            (((((((((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int)) shl 8) or (((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int))) as kotlin.Int)) shl 16) or (((((((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int)) shl 8) or (((((nsVerifier.Companion.eError).toInt() shl 4) or (nsVerifier.Companion.eError).toInt()) as kotlin.Int))) as kotlin.Int)))



        charset = "UTF-8"
        stFactor = 16
    }

    override fun isUCS2(): Boolean {
        return false
    }


    companion object {
        var cclass: IntArray? = null
        var states: IntArray? = null
        var stFactor: Int = 0
        var charset: String? = null
    }
}
