[versions]
agp = "8.8.2"
cameraView = "1.4.2"
guava = "29.0-android"
itext7Core = "9.2.0"
kotlin = "2.2.0"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.1"
lifecycleProcess = "2.9.1"
material = "1.12.0"
activity = "1.10.1"
constraintlayout = "2.2.1"
billingKtx = "8.0.0"

glide = "4.16.0"
gson = "2.13.1"
lottie = "6.6.7"
review-ktx = "2.0.2"
shimmer = "0.5.0"
koin-android = "4.1.0"
appUpdateKtx = "2.1.0"
inappupdate = "1.1.0"
sdpAndroid = "1.1.1"
sspAndroid = "1.1.1"
azmoduleads = "1.1.9"
firebaseAnalytics = "22.5.0"
firebaseConfig = "22.1.2"
firebaseMessaging = "24.1.2"
firebaseCrashlytics = "19.4.4"
navigationFragmentKtx = "2.9.0"
navigationUiKtx = "2.9.0"
roomRuntime = "2.7.2"
pdfboxAndroid = "2.0.27.0"
androidPdfViewer = "3.2.0-beta.3"
fragment = "1.8.8"
rxjava = "3.1.10"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycleProcess" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }


review-ktx = { module = "com.google.android.play:review-ktx", version.ref = "review-ktx" }
sdp-android = { module = "com.intuit.sdp:sdp-android", version.ref = "sdpAndroid" }
shimmer = { module = "com.facebook.shimmer:shimmer", version.ref = "shimmer" }
ssp-android = { module = "com.intuit.ssp:ssp-android", version.ref = "sspAndroid" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }

androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomRuntime" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }


glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
inappupdate = { module = "com.azuraglobal:inappupdate", version.ref = "inappupdate" }
app-update-ktx = { module = "com.google.android.play:app-update-ktx", version.ref = "appUpdateKtx" }
azmoduleads = { module = "com.azuraglobal:azmoduleads", version.ref = "azmoduleads" }
billing-ktx = { module = "com.android.billingclient:billing-ktx", version.ref = "billingKtx" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics", version.ref = "firebaseAnalytics" }
firebase-config = { group = "com.google.firebase", name = "firebase-config", version.ref = "firebaseConfig" }
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging", version.ref = "firebaseMessaging" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics", version.ref = "firebaseCrashlytics" }

koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin-android" }
koin-android-compat = { module = "io.insert-koin:koin-android-compat", version.ref = "koin-android" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin-android" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }
androidx-fragment = { group = "androidx.fragment", name = "fragment", version.ref = "fragment" }

pdfbox-android = { module = "com.tom-roush:pdfbox-android", version.ref = "pdfboxAndroid" }
android-pdf-viewer = { module = "com.github.mhiew:android-pdf-viewer", version.ref = "androidPdfViewer" }


androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "cameraView" }
androidx-camera-core = { module = "androidx.camera:camera-core", version.ref = "cameraView" }
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "cameraView" }
androidx-camera-view = { module = "androidx.camera:camera-view", version.ref = "cameraView" }
rxjava = { module = "io.reactivex.rxjava3:rxjava", version.ref = "rxjava" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
firebaseCrashlytics = { id = "com.google.firebase.crashlytics", version = "3.0.4" }
gmsGoogleServices = { id = "com.google.gms.google-services", version = "4.4.2" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
