plugins {
    alias(libs.plugins.androidLibrary)
}

android {
    compileSdk 37
    namespace "com.yalantis.ucrop"
    defaultConfig {
        minSdkVersion 24

        vectorDrawables.useSupportLibrary = true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }


    lint {
        abortOnError false
    }

}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
    }
}

dependencies {
    implementation libs.androidx.appcompat
    implementation libs.androidx.exifinterface
    implementation libs.androidx.transition
    // OkHttp3 versions above 3.12.x don't support pre-Lollipop Android versions (API 21)
    implementation libs.okhttp
    implementation libs.ssp.android
    implementation libs.sdp.android
    implementation libs.androidx.core.ktx


}
